### ISSUE TITLE
Exposed ipv4 address

### ISSUE THREAD

**Issue by ADettlaff** [digitalocean/marketplace-pi-hole-vpn#7]
Just tested this out of curiosity on an IPv6 enabled droplet.

Default configuration, running "Full VPN" mode. Only the client's IPv6 address is changed to server address. The real IPv4 address is still exposed.

The generated client config looks like this:
```
[Interface]
Address = 10.2.53.2/32, fc10:253::2/128
DNS = 10.2.53.1, fc10:253::1
PrivateKey = xxx

[Peer]
Endpoint = [abcd:abcd:a:ab::abcd:abcd]:51820
PersistentKeepalive = 25
PublicKey = xxx
PresharedKey = xxx
AllowedIPs = 0.0.0.0/0, ::/0
```
Unfortunately there is no useful information on your guide regarding this issue. Please add information on how to prevent this and make sure that both ipv4 and ipv6 is changed.

**Comment by CrashenX** [comment]
@ADettlaff I'm not sure I understand what you are saying. What / how do you expect things to be configured differently than they are?

> Only the client's IPv6 address is changed to server address.

Are you referring to `Endpoint = [abcd:abcd:a:ab::abcd:abcd]:51820` not containing an IPv4 address

> The real IPv4 address is still exposed.

Are you saying that you can still access the VPN over IPv4? If so, this is intentional. Are you wanting this not to be the case?

> how to prevent this

Prevent what?

> make sure that both ipv4 and ipv6 is changed.

Changed? Changed where / how?
